apiVersion: kudo.dev/v1beta1
parameters:
  - name: replicas
    description: Number of replicas that should be run as part of the deployment
    default: 2
  - name: message
    description: cow says
    default: Good+old+version+01
    trigger: updatemsg
  - name: version
    description: app version
    default: v1
    trigger: deploy-new
  - name: original
    description: app version
    default: v1 # v2
  - name: traffic
    description: traffic percentage
    default: 100
    trigger: update-vs