apiVersion: kudo.dev/v1beta1
parameters:
  - name: replicas
    description: Number of replicas that should be run as part of the deployment
    default: 2
  - name: message
    description: cow moos
    default: Some+message
    trigger: updatemsg