apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-{{ .Params.version }}
spec:
  selector:
    matchLabels:
      app: my-server
      version: {{ .Params.version }}
  replicas: {{ .Params.replicas }} # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: my-server
        version: {{ .Params.version }}
    spec:
      volumes:
        - name: pvc0001
          persistentVolumeClaim:
            claimName: pvc0001-{{ .Params.version }}
        - name: www
          configMap:
            name: {{ .Pipes.indexHtml }}
      containers:
        - name: my-server-{{ .Params.version }}
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: pvc0001
            - name: www
              mountPath: /usr/share/nginx/html/