apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0001-{{ .Params.version }}
  version: {{ .Params.version }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
