apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: kudo
    kudo.dev/instance: first-one-instance
    kudo.dev/operator: first-one
  name: my-server-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: my-server