apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001-{{ .Params.version }}
  version: {{ .Params.version }}
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/data